[package]
name = "autortr_rocket"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
autortr_rocket_codegen = { path = "../codegen" }
autortr_rocket_core = { path = "../core" }
autortr_rocket_router = { path = "../router" }
